In [2]:
import pandas as pd

In [7]:
retail_sales = pd.read_csv('../data/retail_sales_dataset.csv')
retail_sales.head(3)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30

In [25]:
# transactions_df['payment_cash'] = pd.Categorical(transactions_df['PaymentMethod'])
# transactions_df['payment_card'].unique()
transactions_df['payment_cash'] = pd.Categorical(transactions_df['PaymentMethod']).codes
transactions_df['payment_cash'].unique()

array([0, 3, 2, 1], dtype=int8)

In [ ]:
from src.get_data import GetData

transactions_df = GetData().sellin_input()

,CustomerID,ProductID,Quantity,Price,TransactionDate,PaymentMethod,StoreLocation,ProductCategory,DiscountApplied(%),TotalAmount,payment_cash,payment_card,payment_credit_card,payment_debit_card,payment_paypal,discount_level
0,109318,C,7,80.079844,12/26/2023 12:32,Cash,"176 Andrew Cliffs\nBaileyfort, HI 93354",Books,18.677100,455.862764,0,0,0,0,0,2
1,993229,C,4,75.195229,8/5/2023 0:00,Cash,"11635 William Well Suite 809\nEast Kara, MT 19483",Home Decor,14.121365,258.306546,0,0,0,0,0,2
2,579675,A,8,31.528816,3/11/2024 18:51,Cash,"910 Mendez Ville Suite 909\nPort Lauraland, MO...",Books,15.943701,212.015651,0,0,0,0,0,2
3,799826,D,5,98.880218,10/27/2023 22:00,PayPal,"87522 Sharon Corners Suite 500\nLake Tammy, MO...",Books,6.686337,461.343769,3,0,0,0,1,1
4,121413,A,7,93.188512,12/22/2023 11:38,Cash,"0070 Michelle Island Suite 143\nHoland, VA 80142",Electronics,4.030096,626.030484,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,726461,A,2,56.078258,7/17/2023 16:59,Credit Card,"3632 Darren Station Apt. 553\nEricaborough, RI...",Clothing,18.345145,91.581240,1,1,1,0,0,2
99996,328056,A,6,88.516406,5/30/2023 9:04,Credit Card,"821 Taylor Shoals\nEvansville, IL 70845",Electronics,3.995541,509.878179,1,1,1,0,0,1
99997,887304,B,4,72.385564,8/25/2023 7:59,Credit Card,"50653 Kara Lakes\nStephanieborough, RI 94492",Clothing,17.423979,239.092472,1,1,1,0,0,2
99998,326401,C,5,66.542239,2/5/2024 19:45,PayPal,"18756 Mcfarland Way Suite 866\nBarnettside, PR...",Electronics,14.345018,284.983717,3,0,0,0,1,2
99999,771566,C,5,38.087766,2/4/2024 11:53,Debit Card,"8046 Hull Drive\nPaulstad, GU 87218",Home Decor,2.966058,184.790305,2,1,0,1,0,1

In [29]:
transactions_df['DiscountApplied(%)'].max()

np.float64(19.99958523)

In [26]:
transactions_df['discount_level'] = pd.cut(
    transactions_df['DiscountApplied(%)'], 
    bins=[-0.1, 0, 10, 20, 100],
    labels=[0, 1, 2, 3]
).astype(int)

transactions_df['discount_level'].unique()

array([2, 1])

In [ ]:
transactions_df = pd.read_csv('../data/Retail_Transaction_Dataset.csv')
transactions_df.head(3)
transactions_df.columns

Index(['CustomerID', 'ProductID', 'Quantity', 'Price', 'TransactionDate',
       'PaymentMethod', 'StoreLocation', 'ProductCategory',
       'DiscountApplied(%)', 'TotalAmount'],
      dtype='str')